<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">We're here to help</h5>
                <p class="grey-text text-lighten-4">NewSite creates custom websites for small businesses to help them
                    reach their customers and achieve their goals. We would love to hear about your business and see how
                    we can help you help your customers.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Sitemap</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="/index.php">Home</a></li>
                    <li><a class="grey-text text-lighten-3" href="/products.php">Products</a></li>
                    <li><a class="grey-text text-lighten-3" href="/aboutus.php">About Us</a></li>
                    <li><a class="grey-text text-lighten-3" href="/faq.php">FAQs</a></li>
                    <li><a class="grey-text text-lighten-3" href="/contact.php">Contact Us</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            &copy;2016 James Hollowell
        </div>
    </div>
</footer>